// <auto-generated />
using System;
using DoAn_DangKyTourDuLich.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAn_DangKyTourDuLich.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260404185730_DataBase")]
    partial class DataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.2.25163.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAn_DangKyTourDuLich.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Tour Trong Nước"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Tour Nước Ngoài"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Tour Biển Đảo"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Tour Núi Rừng"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "Tour Văn Hóa"
                        });
                });

            modelBuilder.Entity("DoAn_DangKyTourDuLich.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DoAn_DangKyTourDuLich.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("TourId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("DoAn_DangKyTourDuLich.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HideReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagesData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("TourId");

                    b.HasIndex("UserId", "BookingId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("DoAn_DangKyTourDuLich.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentParticipants")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartureLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DetailDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountPrice")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrlsData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBeach")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsForGroup")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLowBudget")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMountain")
                        .HasColumnType("bit");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("Schedule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TourCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Transportation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentParticipants = 0,
                            DepartureDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocation = "TP.HCM",
                            Destination = "Kiên Giang",
                            DetailDescription = "Tour nghỉ dưỡng cao cấp.",
                            Duration = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1589782109277-516cd42b8bb7?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            IsBeach = true,
                            IsFeatured = true,
                            IsForGroup = true,
                            IsLowBudget = false,
                            IsMountain = false,
                            MaxParticipants = 30,
                            Name = "Phú Quốc: Nghỉ dưỡng Đảo Ngọc",
                            Price = 5500000m,
                            Schedule = "Sáng: Check-in Grand World - Xem show Tinh hoa Việt Nam | Trưa: Thưởng thức Bún Quậy Kiến Xây | Chiều: Vui chơi VinWonders",
                            ShortDescription = "Vui chơi VinWonders & Safari.",
                            TourCode = "PQ001",
                            Transportation = "Máy bay"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentParticipants = 0,
                            DepartureDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocation = "Phú Quốc",
                            Destination = "Kiên Giang",
                            DetailDescription = "Tour mạo hiểm biển đảo.",
                            Duration = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1557426272-fc759fdf7a8d?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            IsBeach = true,
                            IsFeatured = false,
                            IsForGroup = true,
                            IsLowBudget = true,
                            IsMountain = false,
                            MaxParticipants = 20,
                            Name = "Phú Quốc: Tour 4 Đảo Cano",
                            Price = 1800000m,
                            Schedule = "Sáng: Cano đi Hòn Mây Rút | Trưa: Ăn hải sản bè nổi | Chiều: Check-in Cầu Hôn (Kiss Bridge)",
                            ShortDescription = "Lặn ngắm san hô & Check-in hòn Thơm.",
                            TourCode = "PQ002",
                            Transportation = "Cano"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentParticipants = 0,
                            DepartureDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocation = "TP.HCM",
                            Destination = "Đà Nẵng",
                            DetailDescription = "Nghỉ dưỡng & Giải trí.",
                            Duration = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1559592442-741efca65ca6?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            IsBeach = true,
                            IsFeatured = true,
                            IsForGroup = true,
                            IsLowBudget = false,
                            IsMountain = false,
                            MaxParticipants = 40,
                            Name = "Đà Nẵng: Siêu phẩm Bà Nà Hills",
                            Price = 4200000m,
                            Schedule = "Sáng: Cáp treo Bà Nà - Cầu Vàng | Trưa: Buffet 100 món | Chiều: Vui chơi Fantasy Park",
                            ShortDescription = "Check-in Cầu Vàng - Fantasy Park.",
                            TourCode = "DN001",
                            Transportation = "Máy bay"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentParticipants = 0,
                            DepartureDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocation = "TP.HCM",
                            Destination = "Lâm Đồng",
                            DetailDescription = "Nghỉ dưỡng nhẹ nhàng.",
                            Duration = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1588665042459-7f79f220310e?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            IsBeach = false,
                            IsFeatured = true,
                            IsForGroup = true,
                            IsLowBudget = true,
                            IsMountain = true,
                            MaxParticipants = 25,
                            Name = "Đà Lạt: Thiên đường Sống ảo",
                            Price = 3200000m,
                            Schedule = "Sáng: Vườn hoa Thành phố | Trưa: Ăn Lẩu gà lá é | Chiều: Cafe Still Cafe phong cách Nhật",
                            ShortDescription = "Check-in các vườn hoa & Cafe hot.",
                            TourCode = "DL001",
                            Transportation = "Xe du lịch"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentParticipants = 0,
                            DepartureDate = new DateTime(2026, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocation = "Đà Lạt",
                            Destination = "Lâm Đồng",
                            DetailDescription = "Mạo hiểm núi rừng.",
                            Duration = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1559599189-fe84dea4eb79?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            IsBeach = false,
                            IsFeatured = false,
                            IsForGroup = false,
                            IsLowBudget = true,
                            IsMountain = true,
                            MaxParticipants = 15,
                            Name = "Đà Lạt: Trekking Langbiang",
                            Price = 1500000m,
                            Schedule = "Sáng: 04h00 Săn mây Cầu Đất | Trưa: Picnic đỉnh Langbiang | Chiều: Trượt thác Datanla",
                            ShortDescription = "Chinh phục đỉnh núi - Săn mây.",
                            TourCode = "DL002",
                            Transportation = "Xe Jeep"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentParticipants = 0,
                            DepartureDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocation = "Hà Nội",
                            Destination = "Lào Cai",
                            DetailDescription = "Chinh phục đỉnh cao.",
                            Duration = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1504457047772-27faf1c00561?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            IsBeach = false,
                            IsFeatured = true,
                            IsForGroup = true,
                            IsLowBudget = true,
                            IsMountain = true,
                            MaxParticipants = 25,
                            Name = "Sapa: Chinh phục Fansipan",
                            Price = 3800000m,
                            Schedule = "Sáng: Cáp treo Fansipan ngắm thung lũng | Trưa: Buffet trên núi | Chiều: Bản Cát Cát",
                            ShortDescription = "Cáp treo Fansipan - Bản Cát Cát.",
                            TourCode = "SP001",
                            Transportation = "Xe giường nằm"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentParticipants = 0,
                            DepartureDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocation = "Hà Nội",
                            Destination = "Quảng Ninh",
                            DetailDescription = "Kỳ quan thiên nhiên.",
                            Duration = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            IsBeach = true,
                            IsFeatured = true,
                            IsForGroup = true,
                            IsLowBudget = false,
                            IsMountain = false,
                            MaxParticipants = 40,
                            Name = "Hạ Long: Du thuyền 5 sao",
                            Price = 5500000m,
                            Schedule = "Ngày 1: Lên tàu - Tiệc Sunset trên boong | Trưa: Ăn hải sản | Chiều: Chèo Kayak",
                            ShortDescription = "Ngủ đêm trên vịnh di sản.",
                            TourCode = "HL001",
                            Transportation = "Du thuyền"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentParticipants = 0,
                            DepartureDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocation = "Hà Nội",
                            Destination = "Ninh Bình",
                            DetailDescription = "Di sản kép thế giới.",
                            Duration = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1655712530188-75c1c4e97eb6?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            IsBeach = false,
                            IsFeatured = true,
                            IsForGroup = true,
                            IsLowBudget = true,
                            IsMountain = true,
                            MaxParticipants = 50,
                            Name = "Ninh Bình: Tràng An - Hang Múa",
                            Price = 1500000m,
                            Schedule = "Sáng: Chinh phục Hang Múa ngắm lúa chín | Trưa: Đặc sản thịt dê | Chiều: Thuyền Tràng An",
                            ShortDescription = "Chèo thuyền & Leo núi.",
                            TourCode = "NB001",
                            Transportation = "Xe du lịch"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentParticipants = 0,
                            DepartureDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocation = "Huế",
                            Destination = "Thừa Thiên Huế",
                            DetailDescription = "Tìm về lịch sử.",
                            Duration = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1590424744295-971268634782?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            IsBeach = false,
                            IsFeatured = true,
                            IsForGroup = true,
                            IsLowBudget = true,
                            IsMountain = false,
                            MaxParticipants = 30,
                            Name = "Huế: Cố Đô Trầm Mặc",
                            Price = 1200000m,
                            Schedule = "Sáng: Đại Nội - Chùa Thiên Mụ | Trưa: Cơm cung đình | Chiều: Lăng Khải Định",
                            ShortDescription = "Đại Nội - Lăng Tẩm - Sông Hương.",
                            TourCode = "HUE01",
                            Transportation = "Xích lô"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentParticipants = 0,
                            DepartureDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocation = "Đà Nẵng",
                            Destination = "Quảng Nam",
                            DetailDescription = "Lãng mạn - Hoài niệm.",
                            Duration = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1555921015-5532091f6026?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            IsBeach = false,
                            IsFeatured = true,
                            IsForGroup = true,
                            IsLowBudget = true,
                            IsMountain = false,
                            MaxParticipants = 50,
                            Name = "Hội An: Phố Cổ Lung Linh",
                            Price = 900000m,
                            Schedule = "Chiều: Thăm Chùa Cầu - Làng Gốm | Tối: Thả đèn hoa đăng sông Hoài - Cafe Faifo",
                            ShortDescription = "Đèn lồng - Thả hoa đăng.",
                            TourCode = "HA001",
                            Transportation = "Đi bộ"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentParticipants = 0,
                            DepartureDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocation = "TP.HCM",
                            Destination = "Khánh Hòa",
                            DetailDescription = "Full dịch vụ.",
                            Duration = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1623941457173-0499e0df2438?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            IsBeach = true,
                            IsFeatured = true,
                            IsForGroup = true,
                            IsLowBudget = false,
                            IsMountain = false,
                            MaxParticipants = 50,
                            Name = "Nha Trang: Nghỉ dưỡng Vinpearl",
                            Price = 5200000m,
                            Schedule = "Ngày 1: Cáp treo ra đảo | Ngày 2: VinWonders - Show Nhạc nước | Ngày 3: Tắm bùn khoáng nóng",
                            ShortDescription = "Đảo Hòn Tre - Thiên đường vui chơi.",
                            TourCode = "NT001",
                            Transportation = "Máy bay"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentParticipants = 0,
                            DepartureDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocation = "TP.HCM",
                            Destination = "Bình Thuận",
                            DetailDescription = "Check-in cực hot.",
                            Duration = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1571508601936-6ca847b47ae4?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            IsBeach = true,
                            IsFeatured = true,
                            IsForGroup = true,
                            IsLowBudget = true,
                            IsMountain = false,
                            MaxParticipants = 30,
                            Name = "Mũi Né: Săn Hoàng Hôn Bàu Trắng",
                            Price = 1500000m,
                            Schedule = "Sáng: Săn bình minh đồi cát | Trưa: Ăn bánh xèo | Chiều: Xe Jeep địa hình Bàu Trắng",
                            ShortDescription = "Đồi cát trắng - Xe Jeep.",
                            TourCode = "MN001",
                            Transportation = "Xe du lịch"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentParticipants = 0,
                            DepartureDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocation = "TP.HCM",
                            Destination = "TP. Hồ Chí Minh",
                            DetailDescription = "Sài Gòn hoa lệ.",
                            Duration = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1583417311718-c29e46a7be7f?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            IsBeach = false,
                            IsFeatured = true,
                            IsForGroup = true,
                            IsLowBudget = true,
                            IsMountain = false,
                            MaxParticipants = 40,
                            Name = "Sài Gòn: Ngắm sông từ Bitexco",
                            Price = 1100000m,
                            Schedule = "Sáng: Dinh Độc Lập - Nhà Thờ Đức Bà | Trưa: Cơm tấm | Chiều: Landmark 81",
                            ShortDescription = "Dinh Độc Lập - Bưu Điện - Landmark.",
                            TourCode = "HCM01",
                            Transportation = "Xe buýt 2 tầng"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentParticipants = 0,
                            DepartureDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocation = "TP.HCM",
                            Destination = "Bà Rịa - Vũng Tàu",
                            DetailDescription = "Lộng lẫy - Cổ điển.",
                            Duration = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1563298723-dcfebaa392e3?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            IsBeach = true,
                            IsFeatured = true,
                            IsForGroup = true,
                            IsLowBudget = false,
                            IsMountain = false,
                            MaxParticipants = 20,
                            Name = "Vũng Tàu: Nghỉ dưỡng The Imperial",
                            Price = 4500000m,
                            Schedule = "Ngày 1: Đón khách - Tea party | Ngày 2: Tắm biển riêng - Thăm Bạch Dinh",
                            ShortDescription = "Khách sạn phong cách Victoria.",
                            TourCode = "VT001",
                            Transportation = "Xe du lịch"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentParticipants = 0,
                            DepartureDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocation = "TP.HCM",
                            Destination = "Cần Thơ",
                            DetailDescription = "Văn hóa miền Tây.",
                            Duration = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1599321451299-a1b7e466ce78?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            IsBeach = false,
                            IsFeatured = true,
                            IsForGroup = true,
                            IsLowBudget = true,
                            IsMountain = false,
                            MaxParticipants = 50,
                            Name = "Cần Thơ: Chợ Nổi & Miệt Vườn",
                            Price = 1200000m,
                            Schedule = "Ngày 1: Thăm nhà cổ Bình Thủy | Ngày 2: 05h00 Chợ nổi Cái Răng - Vườn Mỹ Khánh",
                            ShortDescription = "Cái Răng - Mỹ Khánh - Sông nước.",
                            TourCode = "CT001",
                            Transportation = "Xe du lịch"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentParticipants = 0,
                            DepartureDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocation = "TP.HCM",
                            Destination = "Thái Lan",
                            DetailDescription = "Tour du lịch giải trí.",
                            Duration = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1504214208698-ea1919a2f9e0?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            IsBeach = true,
                            IsFeatured = true,
                            IsForGroup = true,
                            IsLowBudget = false,
                            IsMountain = false,
                            MaxParticipants = 30,
                            Name = "Thái Lan: Nghỉ dưỡng Pattaya biển xanh",
                            Price = 6990000m,
                            Schedule = "Sáng: Bay đến Bangkok | Trưa: Lẩu Thái Tomyum | Chiều: Tắm biển Đảo San Hô | Tối: Xem show Alcazar",
                            ShortDescription = "Đảo San Hô - Show chuyển giới Alcazar.",
                            TourCode = "THAI1",
                            Transportation = "Máy bay"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentParticipants = 0,
                            DepartureDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocation = "TP.HCM",
                            Destination = "Nhật Bản",
                            DetailDescription = "Kỳ nghỉ đẳng cấp.",
                            Duration = 6,
                            ImageUrl = "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            IsBeach = false,
                            IsFeatured = true,
                            IsForGroup = true,
                            IsLowBudget = false,
                            IsMountain = true,
                            MaxParticipants = 20,
                            Name = "Nhật Bản: Nghỉ dưỡng Núi Phú Sĩ",
                            Price = 28900000m,
                            Schedule = "Sáng: Thăm làng cổ Oshino Hakkai | Trưa: Mì Ramen | Chiều: Tắm khoáng nóng Onsen ngắm Núi Phú Sĩ",
                            ShortDescription = "Tắm Onsen - Ngắm núi Phú Sĩ.",
                            TourCode = "JPN01",
                            Transportation = "Máy bay"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentParticipants = 0,
                            DepartureDate = new DateTime(2026, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocation = "TP.HCM",
                            Destination = "Hàn Quốc",
                            DetailDescription = "Mùa thu vàng rực rỡ.",
                            Duration = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            IsBeach = false,
                            IsFeatured = true,
                            IsForGroup = true,
                            IsLowBudget = false,
                            IsMountain = true,
                            MaxParticipants = 25,
                            Name = "Hàn Quốc: Nghỉ dưỡng Đảo Nami",
                            Price = 15900000m,
                            Schedule = "Sáng: Di chuyển đến đảo Nami | Trưa: Gà nướng cay | Chiều: Check-in hàng cây ngân hạnh",
                            ShortDescription = "Phim trường lãng mạn - Nami Island.",
                            TourCode = "KOR01",
                            Transportation = "Máy bay"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentParticipants = 0,
                            DepartureDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocation = "TP.HCM",
                            Destination = "Singapore",
                            DetailDescription = "Trải nghiệm sang trọng.",
                            Duration = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            IsBeach = false,
                            IsFeatured = true,
                            IsForGroup = true,
                            IsLowBudget = false,
                            IsMountain = false,
                            MaxParticipants = 25,
                            Name = "Singapore: Nghỉ dưỡng Marina Bay Sands",
                            Price = 12500000m,
                            Schedule = "Sáng: Thăm Garden by the Bay | Trưa: Cơm gà Hải Nam | Chiều: Tắm hồ bơi vô cực cao nhất thế giới",
                            ShortDescription = "Hồ bơi vô cực - Garden by the Bay.",
                            TourCode = "SIN01",
                            Transportation = "Máy bay"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentParticipants = 0,
                            DepartureDate = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocation = "TP.HCM",
                            Destination = "Pháp",
                            DetailDescription = "Tour lãng mạn mộng mơ.",
                            Duration = 7,
                            ImageUrl = "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            IsBeach = false,
                            IsFeatured = true,
                            IsForGroup = true,
                            IsLowBudget = false,
                            IsMountain = false,
                            MaxParticipants = 15,
                            Name = "Pháp: Nghỉ dưỡng bên dòng sông Seine",
                            Price = 65000000m,
                            Schedule = "Sáng: Thăm Tháp Eiffel | Trưa: Ăn món Pháp | Chiều: Du thuyền sông Seine | Tối: Rượu vang Pháp",
                            ShortDescription = "Tháp Eiffel - Bảo tàng Louvre.",
                            TourCode = "FRA01",
                            Transportation = "Máy bay"
                        });
                });

            modelBuilder.Entity("DoAn_DangKyTourDuLich.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DoAn_DangKyTourDuLich.Models.Order", b =>
                {
                    b.HasOne("DoAn_DangKyTourDuLich.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoAn_DangKyTourDuLich.Models.OrderDetail", b =>
                {
                    b.HasOne("DoAn_DangKyTourDuLich.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_DangKyTourDuLich.Models.Tour", "Tour")
                        .WithMany("OrderDetails")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("DoAn_DangKyTourDuLich.Models.Review", b =>
                {
                    b.HasOne("DoAn_DangKyTourDuLich.Models.Order", "Booking")
                        .WithMany("Reviews")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_DangKyTourDuLich.Models.Tour", "Tour")
                        .WithMany("Reviews")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoAn_DangKyTourDuLich.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoAn_DangKyTourDuLich.Models.Tour", b =>
                {
                    b.HasOne("DoAn_DangKyTourDuLich.Models.Category", "Category")
                        .WithMany("Tours")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DoAn_DangKyTourDuLich.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DoAn_DangKyTourDuLich.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_DangKyTourDuLich.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DoAn_DangKyTourDuLich.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoAn_DangKyTourDuLich.Models.Category", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("DoAn_DangKyTourDuLich.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("DoAn_DangKyTourDuLich.Models.Tour", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("DoAn_DangKyTourDuLich.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
